# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ff44cfbd8b80c5c7ca463fc59427967b5e443c9aaa1ad2424cb9ac1b7740663748130ede1d9427a75677b57ba7a5825d0c48beae42c040a7ab317c049faca6c

test:
  secret_key_base: 19f8e652ab0a889f62daaee6db999ed66643da65bd43e047fe790227a5b606230c0a11a2df5fed2fc345ae267243e019deff01c35c695ff7da10da69ed3111eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
